# Generated by Django 4.2.1 on 2023-05-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_auto_20210423_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizusuario',
            name='cantidad_preguntas',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de preguntas'),
        ),
    ]
